export enum ActionTypes {
  LOGIN = 'LOGIN',
  REPO = 'REPO',
  BLACKLIST = 'BLACKLIST',
  REVIEWER = 'REVIEWER',
  AVATAR = 'AVATAR',
  BASELOADING = 'BASELOADING',
  LOADSHOWREVIEWER = 'LOADREADYSHOWREVIEWER'
}
