export enum ActionTypes {
  LOGIN = 'LOGIN',
  REPO = 'REPO',
  BLACKLIST = 'BLACKLIST',
  TOTAL_DATA_USER = "TOTAL_DATA_USER",
  REVIEWER = 'REVIEWER',
  GENERATE_REVIEWER_IMGS = 'GENERATE_REVIEWER',
  LOADING_DATA_USER = 'LOADING_DATA_USER',
  LOAD_SHOW_REVIEWER = 'LOAD_READY_SHOW_REVIEWER'
}
