export enum ActionTypes {
  LOGIN = 'LOGIN',
  REPO = 'REPO',
  BLACKLIST = 'BLACKLIST',
  TOTAL_DATA_USER = "TOTAL_DATA_USER",
  REVIEWER = 'REVIEWER',
  AVATAR = 'AVATAR',
  BASE_LOADING = 'BASELOADING',
  LOAD_SHOW_REVIEWER = 'LOADREADYSHOWREVIEWER'
}
